apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "promotion", "namespace": "", "kind": "DeploymentConfig"}]'
    name: service-pipeline
  spec:
    source:
      git:
        ref: pipeline
        uri: https://github.com/tancheeyong/karaf2-cxf-rest.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic
